config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  get "contacts_servers/assign"

  resources :contacts


  authenticated :user do
    root :to => 'servers#index'
  end

  root :to => "home#index"

  devise_for :users
  resources :servers
  resources :contacts
  resources :users, :only => [:show, :index]

  resources :servers do
    resources :contacts_servers
  end

  resources :contacts_servers
  match "servers/:server_id/contacts_servers/assign" => "contacts_servers#assign", as: :assign 
  match "servers/:server_id/contacts/:id" => "contacts#destroy", as: :destroy

	namespace :api do
		namespace :v1  do
	  	resource :sessions, only: [:create, :destroy]
	  	resources :servers, except: [:new, :edit]
      match 'sessions', :controller => 'sessions', :action => 'destroy', :constraints => {:method => 'OPTIONS'}
	  end
	end
end

app/models/server.rb
class Server < ActiveRecord::Base
  attr_accessible :name, :status, :url

  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :url, presence: true, 
            format: { :with => /^(http|https):\/\/([a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}|(25[0-5]|2[0-4]\d|[0-1]?\d?\d)(\.(25[0-5]|2[0-4]\d|[0-1]?\d?\d)){3}|localhost)(:[0-9]{1,5})?(\/.*)?$/ix }

  after_create :update_status

  belongs_to :user
  has_many :contacts_server
  has_many :contacts,:through => :contacts_server


  def update_status
    link_status = LinkStatus.new full_uri
    update_attribute(:status, interpreat_status(link_status.status))
    touch(:updated_at)
  end

  def self.update_statuses
    all.each do |server|
      server.update_status
      Server.server_notification_mail(server)
      @serverhistory = ServerHistory.new(server_id:server.id, status:server.status)
      @serverhistory.save
    end
  end

  def full_uri
    url
  end

  def interpreat_status(code)
    if ((200..206).to_a + (300..307).to_a).include?(code)
      "up"
    elsif ((400..417).to_a + (500..505).to_a).include?(code)
      "down"
    else
      "error"
    end
  end

  def self.server_notification_mail(server)
    if ServerHistory.last_status(server.id) != "no_record"
      if server.status != ServerHistory.last_status(server.id)
        user = User.find_by_id(server.user_id)
        recipients = []
        recipients << user.email
        rec = server.contacts
        rec.each do |r|
          recipients << r.email
        end
        if server.status == "down"
          Notifier.down_email(recipients, server).deliver
        elsif server.status == "up"
          downtime = ServerHistory.downtime(server)
          Notifier.up_email(recipients, server, downtime).deliver
        else
          
        end
      end
    end
    

  end

end

app/controllers/api/v1/servers_controller.rb
class Api::V1::ServersController < Api::V1::BaseController
	# /api/v1/servers(.:format)
	def index
		@servers = current_user.servers
		respond_with(@servers)
	end

	# GET    /api/v1/servers/:id(.:format)
	def show
		@server = current_user.servers.find(params[:id])
		respond_with(@server)
	end

	# POST   /api/v1/servers(.:format)
	def create
		@server = Server.new(params[:server])
		@server.save
		respond_with(@server)
	end

	# PUT    /api/v1/servers/:id(.:format)
	def update
		@server = current_user.servers.find(params[:id])
		@server.update_attributes(params[:server])
		respond_with(@server)
	end

	# DELETE /api/v1/servers/:id(.:format)
	def destroy
		@server = current_user.servers.find(params[:id])
		@server.destroy
		respond_with(@server)
	end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_filter :authenticate_user!

  # GET /servers
  # GET /servers.json
  def index
    @servers = current_user.servers
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
    @server = current_user.servers.find(params[:id])
  end

  # GET /servers/new
  # GET /servers/new.json
  def new
    @server = current_user.servers.new
  end

  # GET /servers/1/edit
  def edit
    @server = current_user.servers.find(params[:id])
    @contact = current_user.contacts.new
    # @server_id = params[:id].to_i
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = current_user.servers.new(params[:server])

      if @server.save
        redirect_to servers_path, notice: 'A new Server was successfully created.'
      else
        render action: "new"
      end
  end

  # PUT /servers/1
  # PUT /servers/1.json
  def update
    @server = current_user.servers.find(params[:id])

      if @server.update_attributes(params[:server])
        redirect_to @server, notice: 'Server was successfully updated.'
      else
        render action: "edit"
      end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server = current_user.servers.find(params[:id])
    @server.destroy
    redirect_to servers_url
  end
end

app/helpers/api/v1/servers_helper.rb
module Api::V1::ServersHelper
end

app/helpers/servers_helper.rb
module ServersHelper
  def colourize_status(status)
    if status == "up"
      content_tag(:span, "UP", class: "label label-success")
    elsif status == "down"
      content_tag(:span, "DOWN", class: "label label-important")
    else
      content_tag(:span, "ERROR", class: "label label-inverse")
    end
  end
end

app/views/servers/_contacts.html.erb
<% server = @server if @server.present? %>
<div class="widget-box">
    <div class="widget-title">
        <h5>Contacts</h5>
        <div class="buttons">
          <%= link_to '#', class: 'btn btn-mini btn-success',  title: "add new contact", id:'new_contact_link', 'data-toggle' =>"modal", 'data-target' =>"#contactModal" do %>
            <i class="icon-plus-sign icon-white"></i> Add New Contact
          <% end %>
        </div>
    </div>
    <div class="widget-content nopadding">
        <table id="table_already_added_contacts" class="table table-striped table-hover">
            <thead>
            
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                    </th>
                </tr>
            </thead>
        <tbody>
            
            <% contacts_added = server.contacts.reverse %>
            <% contacts_added.each do |contact| %>
                <tr>
                    <td>
                        <%= contact.name %>
                    </td>
                    <td>
                        <%= contact.email %>
                    </td>
                    <td>
                      <%= link_to server_contacts_server_path(server, contact), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, title: "destroy" do %>
                        <i class="icon-trash"></i>
                      <% end %>
                    </td>
                </tr>
                
                <% end %>
            <tbody>
        </table>
                
    </div>
</div>                

app/views/servers/_form.html.erb
<div class="widget-content nopadding">
	<%= simple_form_for(@server) do |f| %>
    	<%= f.input :name %>
      	<%= f.input :url %>
        
        <div class="form-actions">
         	<%= f.button :submit, class:'btn btn-primary' %>
        </div>
    <% end %>
</div>
          
          

app/views/servers/_form2.html.erb
<%= simple_form_for @contact, url: server_contacts_servers_path(@server) ,remote: true do |f| %>
    <%= f.input :name %>
    <%= f.input :email %>
    <div class="form-actions">
        <%= f.button :submit, class:'btn btn-primary' %>
    </div>
<% end %>

app/views/servers/_head_javascript_content.html.erb
<script type="text/javascript">
    var availableContacts = <%= raw Contact.populate_contacts(current_user, @server.id) %> ;
    $(document).ready(function () {
        $('#contact').typeahead({

            source: function (query, process) {
                names = [];
                map = {};


                $.each(availableContacts, function (i, name) {
                    var q = name.name + "  \"" + name.email + "\"";
                    map[q] = name;
                    names.push(q);
                });
                process(names);
            },

            updater: function (item) {

                $('#form_search_contacts').attr('action', '/servers/' + <%= @server.id %> +'/contacts_servers/' + map[item].id);
                return item;
            }
        });

        $('#new_contact_link').click(function () {
            $('#new_contact_div').toggle();
        });

    });
</script>

app/views/servers/edit.html.erb
<div class="widget-box">
    <div class="widget-title">
        <h5>
            Edit Server
        </h5>
    </div>
  
    <%= render 'form' %>
    
    
    <div id="head_javascript">
        <%= render partial: "head_javascript_content" %>
    </div>
    <div class="widget-box">
        <div class="widget-title">
            <h5>
                Add Contact
            </h5>
          
        </div>
        <div class="widget-content nopadding">
            <div class="controls margin_top" style="margin-top:10px; margin-bottom:10px; margin-left:10px;">
                <%= form_tag server_contacts_servers_path(@server.id), method: :put, remote:true, class:'form-search', id:'form_search_contacts' do %>
                    <input type="text" id="contact" placeholder="Search Contacts" data-provide="typeahead" autocomplete="off" class="ui-autocomplete-input" />
                    <%= submit_tag "Add", class:'btn btn-primary' %>
                <% end %>
                  
            </div>
        </div>
              
     </div>
            
            
            
    <div id="already_added_contacts">
        <%= render 'contacts' %>
    </div>
              
              
    <!-- Modal -->
    <div id="contactModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="contactModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                ×
            </button>
            <h3 id="contactModalLabel">
                New Contact
            </h3>
        </div>
        <div class="modal-body">
            <div class="widget-box">
                <div class="widget-title">
                    <h5>
                        New Contact
                    </h5>
                </div>
                    
                <div class="widget-content nopadding">
                <div id="contactDynamicContent">    
                    <%= render 'form2' %>
                </div>
            </div>
        
    </div>
</div>    
                          

app/views/servers/index.html.erb
<div class="widget-box">
  <div class="widget-title">
<!--     <span class="icon">
      <i class="icon-th-list"></i>
    </span> -->
    <h5>Servers Current Status</h5>
    <div class="buttons">
      <%= link_to root_path, class: 'btn btn-mini btn-info',  title: "refresh" do %>
        <i class="icon-refresh icon-white"></i> Refresh
      <% end %>
      <%= link_to new_server_path, class: 'btn btn-mini btn-success',  title: "add new server" do %>
        <i class="icon-plus-sign icon-white"></i> Add New Server
      <% end %>
    </div>
  </div>
  <div class="widget-content">
  <ul class="stat-boxes">
    <% @servers.each do |server| %>
    <li class="popover-visits" data-original-title="" title="">
      <div class="left">
        <span>
          <%= colourize_status server.status %>
        </span>
          <!-- <%#= link_to server, title: "show" do %><i class="icon-road"></i><%# end %> -->
          <%= link_to edit_server_path(server), title: "edit" do %><i class="icon-pencil"></i><% end %>
          <%= link_to server, method: :delete, data: { confirm: 'Are you sure?' }, title: "destroy" do %><i class="icon-trash"></i><% end %>
      </div>
      <div class="right">
        <nobr><%= link_to truncate(server.name, length: 25), server.full_uri, title: server.full_uri, target: '_blank' %></nobr>
      </br>
        <nobr class="last-updated-at"><%= "#{distance_of_time_in_words_to_now(server.updated_at)} ago" %></nobr>
      </div>
    </li>
    <% end %>
  </ul>
  </div>
</div>

app/views/servers/new.html.erb
<div class="widget-box">
    <div class="widget-title">
        <span class="icon">
            <i class="icon-align-justify">
            </i>
        </span>
        <h5>
            New Server
        </h5>
    </div>
  
 <%= render 'form' %>
    
    
    

app/views/servers/show.html.erb
<p id="notice">
	<%= notice %>
</p>
<p>
 	<b>Name:</b>
  	<%= @server.name %>
</p>
<p>
	<b>Url:</b>
  	<%= @server.full_uri %>
</p>
<p>
	<b>Status:</b>
  	<%= @server.status %>
</p>
<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>