config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  get "contacts_servers/assign"

  resources :contacts


  authenticated :user do
    root :to => 'servers#index'
  end

  root :to => "home#index"

  devise_for :users
  resources :servers
  resources :contacts
  resources :users, :only => [:show, :index]

  resources :servers do
    resources :contacts_servers
  end

  resources :contacts_servers
  match "servers/:server_id/contacts_servers/assign" => "contacts_servers#assign", as: :assign 
  match "servers/:server_id/contacts/:id" => "contacts#destroy", as: :destroy

	namespace :api do
		namespace :v1  do
	  	resource :sessions, only: [:create, :destroy]
	  	resources :servers, except: [:new, :edit]
      match 'sessions', :controller => 'sessions', :action => 'destroy', :constraints => {:method => 'OPTIONS'}
	  end
	end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  has_many :contacts_server
  has_many :servers,through: :contacts_server
  attr_accessible :email, :name
  attr_accessible :email, :name, :user_id
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, :format => { :with => /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/,
    :message => "Invalid Email" }

  def self.populate_contacts(current_user, server_id)
    server = Server.find server_id
    already_added_contact_ids = server.contacts.map {|c| c.id}
    if already_added_contact_ids.empty?
       contacts = Contact.where('user_id=?',current_user.id).select([:name, :email, :id])
    else
       contacts = Contact.where('user_id=? and id NOT IN (?)',current_user.id, already_added_contact_ids).select([:name, :email, :id])
    end
    return contacts.to_json
  end
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authenticate_user!
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts.all


  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = current_user.contacts.find(params[:id])

  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = current_user.contacts.new

  end

  # GET /contacts/1/edit
  def edit
    @contact = current_user.contacts.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = current_user.contacts.new(name:params[:name], email:params[:email])
    @contact = current_user.contacts.new(params[:contact])
    @server_id = params[:server_id].to_i
    @contact.save
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = current_user.contacts.find(params[:id])
    @contact.update_attributes(params[:contact])
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = current_user.contacts.find(params[:id])
    @contact.destroy
    @contacts = current_user.contacts.all.reverse

    @server_id = params[:server_id].to_i
    if @server_id
      respond_to do |format|
        format.html { redirect_to contacts_url }
        format.js
      end   
    else
     redirect_to contacts_url
    end 
    
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contacts.html.erb
<div class="widget-content nopadding">
    <table id="contacts_listing" class="data-table table table-striped table-hover">
        <thead>
      
        <tr>
            <th>
                Name
            </th>
            <th>
                Email
            </th>
            <th>
                
            </th>
        </tr>
        </thead>
        <tbody>
      
            <% @contacts.each do |contact| %>
                <tr>
                    <td>
                        <%= contact.name %>
                    </td>
                    <td>
                        <%= contact.email %>
                    </td>
                    <td>
                        <%= link_to edit_contact_path(contact), 'data-toggle' =>"modal", 'data-target' =>"#contactModal", title: "edit", class: "edit_contact", 'data-title' => "Edit Contact" do  %>
                        <i class="icon-edit">
                        </i>
                        <% end %>
                        <%= link_to contact, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, title: "destroy" do %>
                        <i class="icon-trash">
                        </i>
                        <% end %>
                    </td>
                </tr>
                <% end %>
        <tbody>
    </table>
                    
</div>
                  
<!-- Modal -->
<div id="contactModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="contactModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
        </button>
        <h3 id="contactModalLabel">Modal header</h3>
    </div>
    <div class="modal-body">
        <p>Loading…</p>
    </div>
</div>

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact, remote:true) do |f| %>
  	<%= f.input :name %>
  	<%= f.input :email %>
        
  	<div class="form-actions">
      	<%= f.button :submit, class:'btn btn-primary' %>
      </div>
<% end %>

app/views/contacts/create.js.erb
<% if @contact && @contact.errors.any? -%>
	$("#contactDynamicContent").html(
		"<%= escape_javascript( render(:partial => "contacts/form", :locals => {:@contact => @contact}) ) %>"
		);
<% else %>
	<% @contacts = current_user.contacts.all.reverse %>
	$("#contactModal").modal('hide');
	$("#all_contacts").html("<%= escape_javascript(render partial: 'contacts/contacts', locals: {contacts: @contacts}) %>");
	$('#contacts_listing').dataTable({
	    "bJQueryUI": true,
	    "sPaginationType": "full_numbers",
	    "sDom": '<"">t<"F"fp>',
	    "aaSorting": []
	});	
<% end %>

app/views/contacts/destroy.js.erb
$("#all_contacts").html("<%= escape_javascript(render partial: 'contacts/contacts', locals: {contacts: @contacts}) %>");
$('#contacts_listing').dataTable({
    "bJQueryUI": true,
    "sPaginationType": "full_numbers",
    "sDom": '<"">t<"F"fp>',
    "aaSorting": []
});

app/views/contacts/edit.html.erb
<div id="contactDynamicContent">
    <%= render 'form' %>
</div>
    
    

app/views/contacts/index.html.erb
<div class="widget-box">
    <div class="widget-title">
        <h5>
            Contacts
        </h5>
        <div class="buttons">
            <%= link_to 'New Contact', new_contact_path, class: "btn btn-mini new_contact", 'data-toggle' =>"modal", 'data-title' => "New Contact" ,'data-target' =>"#contactModal" do %>
            <i class="icon-plus-sign icon-white"></i> Add New Contact
            <% end %> 
        </div>
    </div>
    <div id="all_contacts">
        <%= render 'contacts' %>
    </div>
</div>
    
    

app/views/contacts/new.html.erb
<div id="contactDynamicContent">
    <%= render 'form' %>
</div>
    
    
    
    
    

app/views/contacts/show.html.erb
<p id="notice">
    <%= notice %>
</p>
<p>
    <b>
        Name:
    </b>
    <%= @contact.name %>
</p>
<p>
    <b>
        Email:
    </b>
        <%= @contact.email %>
</p>
<%= link_to 'Edit', edit_contact_path(@contact), class:'btn btn-success' %>
        
        

app/views/contacts/update.js.erb
<% if @contact && @contact.errors.any? -%>
	$("#contactDynamicContent").html(
		"<%= escape_javascript( render(:partial => "contacts/form", :locals => {:@contact => @contact}) ) %>"
		);
<% else %>
	<% @contacts = current_user.contacts.all.reverse %>
	$("#contactModal").modal('hide');
	$('#contactModal').on('hidden', function() {
	    $(this).data('modal').$element.removeData();
	})
	$("#all_contacts").html("<%= escape_javascript(render partial: 'contacts/contacts', locals: {contacts: @contacts}) %>");
	$('#contacts_listing').dataTable({
	    "bJQueryUI": true,
	    "sPaginationType": "full_numbers",
	    "sDom": '<"">t<"F"fp>',
	    "aaSorting": []
	});	
<% end %>