config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  get "contacts_servers/assign"

  resources :contacts


  authenticated :user do
    root :to => 'servers#index'
  end

  root :to => "home#index"

  devise_for :users
  resources :servers
  resources :contacts
  resources :users, :only => [:show, :index]

  resources :servers do
    resources :contacts_servers
  end

  resources :contacts_servers
  match "servers/:server_id/contacts_servers/assign" => "contacts_servers#assign", as: :assign 
  match "servers/:server_id/contacts/:id" => "contacts#destroy", as: :destroy

	namespace :api do
		namespace :v1  do
	  	resource :sessions, only: [:create, :destroy]
	  	resources :servers, except: [:new, :edit]
      match 'sessions', :controller => 'sessions', :action => 'destroy', :constraints => {:method => 'OPTIONS'}
	  end
	end
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<div class="row-fluid">
  <div class="span12">
	  <div class="alert alert-<%= name == :notice ? "info" : "error" %>">
	    <a class="close" data-dismiss="alert">&#215;</a>
	    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
	  </div>  
  </div>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "serverup?", root_path, class: 'brand' %>
<ul class="nav pull-right">  
  <li>
    <%= link_to 'Login', new_user_session_path %>
  </li>
  <li>
    <%= link_to 'Sign up', new_user_registration_path %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= content_for?(:title) ? yield(:title) : "serverup?" %></title>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="header">
      <h1><a href="/">Serverup?</a></h1>   
    </div>
    <!-- <div id="search">
      <input type="text" placeholder="Search here..."><button type="submit" class="tip-right" title="" data-original-title="Search"><i class="icon-search icon-white"></i></button>
    </div> -->
    <div id="user-nav" class="navbar navbar-inverse">
        <ul class="nav btn-group" style="width: auto; margin: 0px;">
            <li class="btn btn-inverse">
              <%= link_to edit_user_registration_path do %>
                <i class="icon icon-user"></i> <span class="text">Profile</span>
              <% end %>
            </li>
            <li class="btn btn-inverse">
              <%= link_to destroy_user_session_path, method: 'delete' do %>
                <i class="icon icon-share-alt"></i> <span class="text">Logout</span>
              <% end %>
            </li>
        </ul>
    </div>
    <div id="sidebar">
      <ul style="display: block;">
        <li class="<%= nav_class(contacts_path, 'servers') %>">
          <a href="/"><i class="icon icon-home"></i> <span>Servers</span></a>
        </li>
        <li class="<%= nav_class(contacts_path) %>">
          <%= link_to contacts_path do %>
            <i class="icon icon-user"></i> <span>Contacts</span>
          <% end %>
        </li>
      </ul>
    </div>

    <div id="content">
      <div id="content-header" style="border-bottom: 1px solid rgba(155, 163, 184, 0.44)">
        <h1><%= yield(:page_header).blank? ? params[:controller].capitalize : yield(:page_header) %></h1>
      </div>
<!--  <div id="breadcrumb">
        <a href="/" title="" class="tip-bottom" data-original-title="Go to Home"><i class="icon-home"></i> Home</a>
        <a href="#" class="current"><%= params[:controller].capitalize %></a>
      </div> -->
      <div class="container-fluid">
        <!-- flash notice -->
        <%= render partial: 'layouts/messages' %>
        <!-- end of flash notice -->

        <div class="row-fluid">
          <div class="span12">
            <%= yield %>
          </div> 
        </div>
        
        <div class="row-fluid">
          <div id="footer" class="span12">
            Copyright © 2012· Indus Net Technologies. All Rights Reserved
          </div>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/layouts/non_logged_in_application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= content_for?(:title) ? yield(:title) : "serverup?" %></title>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <style type="text/css">
    	body{padding-top: 60px;}
    </style>
  </head>
  <body>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
          <div class="navbar">
            <div class="navbar-inner">
              <%= render 'layouts/navigation' %>
            </div>
          </div>
          <div class="row main-body">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <hr>
          <footer>
            <p>© serverup? 2012</p>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>